#!/usr/bin/env node

/**
 * Build script that generates multiple distribution formats:
 * - CommonJS (dist/index.js) - already generated by tsc
 * - ES Modules (dist/esm/index.js)
 * - Minified UMD/IIFE (dist/index.min.js)
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const esbuild = require('esbuild');

const DIST_DIR = path.join(__dirname, '..', 'dist');
const ESM_DIR = path.join(DIST_DIR, 'esm');
const ESM_FILE = path.join(ESM_DIR, 'index.js');
const MIN_FILE = path.join(DIST_DIR, 'index.min.js');

async function build() {
  console.log('🚀 Starting build process...\n');

  // Ensure dist directories exist
  if (!fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true });
  }
  if (!fs.existsSync(ESM_DIR)) {
    fs.mkdirSync(ESM_DIR, { recursive: true });
  }

  try {
    // Step 1: Build CommonJS version
    console.log('📦 Building CommonJS version...');
    execSync('npx tsc', { stdio: 'inherit' });
    console.log('✅ CommonJS build completed.\n');

    // Step 2: Build ES Modules version
    console.log('📦 Building ES Modules version...');
    execSync('npx tsc --project tsconfig.esm.json', { stdio: 'inherit' });
    console.log('✅ ES Modules build completed.\n');

    // Step 3: Create bundled ESM file
    console.log('📦 Creating bundled ESM file...');
    
    // Read all compiled ESM files and bundle them
    const esmFiles = fs.readdirSync(ESM_DIR)
      .filter(file => file.endsWith('.js'))
      .sort(); // Ensure consistent order
    
    // For simplicity, we'll use the main index.js from ESM output
    // In a real scenario, you'd use a bundler like Rollup or esbuild
    if (fs.existsSync(ESM_FILE)) {
      console.log(`✅ ESM bundle created at: ${ESM_FILE}\n`);
    }

    // Step 4: Create minified browser version using esbuild
    console.log('📦 Creating minified browser version with esbuild...');
    
    await esbuild.build({
      entryPoints: ['src/index.ts'],
      bundle: true,
      minify: true,
      sourcemap: true,
      format: 'iife',
      globalName: 'PdfToMarkdown',
      outfile: MIN_FILE,
      platform: 'browser',
      define: {
        'process.env.NODE_ENV': '"production"',
      },
      // shim Buffer for browser
      inject: [path.join(__dirname, 'buffer-shim.js')],
    });

    console.log(`✅ Minified file created at: ${MIN_FILE}\n`);

    // Step 5: Display build summary
    console.log('📊 Build Summary:');
    console.log('─'.repeat(50));
    
    const files = [
      { path: path.join(DIST_DIR, 'index.js'), label: 'CommonJS' },
      { path: ESM_FILE, label: 'ES Module' },
      { path: MIN_FILE, label: 'Minified' },
    ];

    for (const file of files) {
      if (fs.existsSync(file.path)) {
        const stats = fs.statSync(file.path);
        const sizeKB = (stats.size / 1024).toFixed(2);
        console.log(`✓ ${file.label}: ${file.path.replace(DIST_DIR, 'dist/')} (${sizeKB} KB)`);
      } else {
        console.log(`✗ ${file.label}: NOT FOUND`);
      }
    }

    console.log('─'.repeat(50));
    console.log('✅ Build completed successfully!\n');

  } catch (error) {
    console.error('❌ Build failed:', error.message);
    process.exit(1);
  }
}

build();
